"""No-Trade Alpha — the discipline-as-alpha measurement.

The central claim of Pantheon Trades is that *not* trading generates
real, measurable alpha — distinct from the alpha generated by the
trades the council approves. This module quantifies that claim.

For every refused trade the council emits a ``Refusal`` record carrying
the signal's market probability, the council's estimate, and the
direction the council declined. When the underlying market later
resolves, ``score_refusal`` computes the realised P&L of the
counterfactual trade — the trade the system declined to take.

The sign convention is the operator-facing convention:

    realised_alpha > 0     refusing saved money / avoided loss
    realised_alpha < 0     refusing cost opportunity / missed profit

Aggregating across refusals gives the *Restraint P&L* — a Sharpe-able
return stream that costs zero LLM-call gas, zero CLOB fees, zero
spread, and zero slippage. It is, in the strictest sense, free alpha
captured by the discipline of refusing.

Prediction-market payoff convention (CLOB / Polymarket / Manifold):

    Buying a YES share at price p:
        outcome = 1 (YES)  →  profit per share = (1 - p)
        outcome = 0 (NO)   →  profit per share = -p

    Buying a NO share at price (1 - p):
        outcome = 0 (NO)   →  profit per share = p
        outcome = 1 (YES)  →  profit per share = -(1 - p)

For a position sized ``S`` USDC, the number of shares is ``S / price``.
The dollar P&L is therefore ``S * profit_per_share / price``.

Implementation is intentionally hermetic — no I/O, no fees model
beyond what the caller supplies, no time-decay. Pure arithmetic on
the inputs. See ``avoided_loss.py`` for the cumulative-ledger view
that consumes this scoring.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Literal


Direction = Literal["YES", "NO"]


@dataclass(frozen=True, slots=True)
class Refusal:
    """One council refusal — recorded at the moment of restraint.

    Attributes
    ----------
    signal_id
        The originating Apollo signal id.
    market_id
        The market the refused trade would have hit.
    direction
        The direction the council declined to take ("YES" or "NO").
    market_probability
        The market's YES probability at refusal time, in [0, 1].
    council_probability
        The council's consensus YES probability at refusal time,
        in [0, 1].
    proposed_size_usdc
        The dollar size the council would have approved if the
        Areopagus gate had not refused. Always positive.
    reason_code
        Short uppercase tag — STALENESS, EDGE, LIQUIDITY, ZEUS_VETO,
        SOLON_VETO, etc. Carried for downstream auditability.
    """

    signal_id: str
    market_id: str
    direction: Direction
    market_probability: float
    council_probability: float
    proposed_size_usdc: float
    reason_code: str

    def __post_init__(self) -> None:
        if not (0.0 <= self.market_probability <= 1.0):
            raise ValueError("market_probability must be in [0, 1]")
        if not (0.0 <= self.council_probability <= 1.0):
            raise ValueError("council_probability must be in [0, 1]")
        if self.proposed_size_usdc < 0.0:
            raise ValueError("proposed_size_usdc must be non-negative")
        if self.direction not in ("YES", "NO"):
            raise ValueError("direction must be 'YES' or 'NO'")


@dataclass(frozen=True, slots=True)
class ScoredRefusal:
    """Result of scoring a refusal against its eventual outcome.

    ``realised_alpha`` carries the operator-facing sign — positive
    when refusing was correct (saved money), negative when refusing
    was wrong (missed profit). ``would_have_pnl`` carries the raw
    counterfactual trade P&L for the auditor view.
    """

    signal_id: str
    market_id: str
    direction: Direction
    outcome: int  # 1 = YES resolved, 0 = NO resolved
    would_have_pnl_usdc: float
    realised_alpha_usdc: float
    reason_code: str


def _counterfactual_pnl(
    *,
    direction: Direction,
    market_probability: float,
    proposed_size_usdc: float,
    outcome: int,
) -> float:
    """Realised P&L of the trade we declined to take.

    Mirrors the standard prediction-market share payoff (see module
    docstring). ``market_probability`` is always the YES side; the
    NO leg pays at price ``(1 - market_probability)``.

    Returns dollar P&L (positive = profit, negative = loss). When
    the market probability touches 0 or 1 on the side the trade
    would have entered, the position is degenerate — return 0 to
    keep the ledger well-defined.
    """
    if outcome not in (0, 1):
        raise ValueError("outcome must be 0 or 1")
    if proposed_size_usdc <= 0.0:
        return 0.0
    if direction == "YES":
        price = market_probability
        if price <= 0.0:
            # Free option — but no share could have actually been
            # bought at zero. Treat as not-executed.
            return 0.0
        profit_per_share = (1.0 - price) if outcome == 1 else -price
        shares = proposed_size_usdc / price
        return shares * profit_per_share
    # NO leg — share costs (1 - market_p), pays 1 if NO wins else 0.
    price_no = 1.0 - market_probability
    if price_no <= 0.0:
        return 0.0
    profit_per_share = (1.0 - price_no) if outcome == 0 else -price_no
    shares = proposed_size_usdc / price_no
    return shares * profit_per_share


def score_refusal(refusal: Refusal, outcome: int) -> ScoredRefusal:
    """Score one refusal against its eventual binary outcome.

    The realised alpha of the refusal is the *negation* of the
    would-have P&L: if the refused trade would have made money, the
    refusal cost us opportunity (negative alpha); if the refused
    trade would have lost money, the refusal saved us (positive
    alpha).
    """
    pnl = _counterfactual_pnl(
        direction=refusal.direction,
        market_probability=refusal.market_probability,
        proposed_size_usdc=refusal.proposed_size_usdc,
        outcome=outcome,
    )
    return ScoredRefusal(
        signal_id=refusal.signal_id,
        market_id=refusal.market_id,
        direction=refusal.direction,
        outcome=outcome,
        would_have_pnl_usdc=pnl,
        realised_alpha_usdc=-pnl,
        reason_code=refusal.reason_code,
    )


@dataclass(frozen=True, slots=True)
class RestraintLedger:
    """Aggregate of scored refusals into a single Restraint-P&L view.

    The fields are dollar quantities; downstream callers can divide by
    ``count`` for averages or by a starting bankroll for percentage
    returns. ``hit_rate`` is the fraction of refusals whose realised
    alpha was strictly positive (refusing was the right call).
    """

    count: int
    cumulative_alpha_usdc: float
    cumulative_would_have_pnl_usdc: float
    hit_rate: float
    best_refusal: ScoredRefusal | None
    worst_refusal: ScoredRefusal | None


def build_ledger(scored: Iterable[ScoredRefusal]) -> RestraintLedger:
    """Fold an iterable of scored refusals into a single ledger."""
    scored_list = list(scored)
    n = len(scored_list)
    if n == 0:
        return RestraintLedger(
            count=0,
            cumulative_alpha_usdc=0.0,
            cumulative_would_have_pnl_usdc=0.0,
            hit_rate=0.0,
            best_refusal=None,
            worst_refusal=None,
        )
    cum_alpha = sum(s.realised_alpha_usdc for s in scored_list)
    cum_pnl = sum(s.would_have_pnl_usdc for s in scored_list)
    hits = sum(1 for s in scored_list if s.realised_alpha_usdc > 0.0)
    best = max(scored_list, key=lambda s: s.realised_alpha_usdc)
    worst = min(scored_list, key=lambda s: s.realised_alpha_usdc)
    return RestraintLedger(
        count=n,
        cumulative_alpha_usdc=cum_alpha,
        cumulative_would_have_pnl_usdc=cum_pnl,
        hit_rate=hits / n,
        best_refusal=best,
        worst_refusal=worst,
    )
